export { Description as ShorDescription } from './Description'
export { Main as ShorMain } from './Main'
export { Sources as ShorSources } from './Sources'
export { Stuff as ShorStuff } from './Stuff'
export { Tech as ShorTech } from './Tech'
export { Tools as ShorTools } from './Tools'
export { Video as ShorVideo } from './Video'
