export const audioMapping = {
  BortTools: 'bort_tools.mp3',
  Bort: 'bort_main.mp3',
  BortDescription: 'bort_description.mp3',
  BortStuff: 'bort_stuff.mp3',
  BortTech: 'bort_tech.mp3',
  Shor: 'shor_main.mp3',
  ShorStuff: 'shor_stuff.mp3',
  ShorTools: 'shor_tools.mp3',
  ShorDescription: 'shor_description.mp3',
  BerestStuff: 'berest_stuff.mp3',
  BerestDescription: 'berest_description.mp3',
  BerestTech: 'berest_tech.mp3',
  Berest: 'berest_main.mp3',
  Wood: 'wood_main.mp3',
  WoodTools: 'wood_tools.mp3',
  WoodDescription: 'wood_description.mp3',
  WoodTech: 'wood_tech.mp3',
  TextileChenTech: 'textile_chen_tech.mp3',
  TextileChenTools: 'textile_chen_tools.mp3',
  TextileChenStuff: 'textile_chen_stuff.mp3',
  TextileChenDescription: 'textile_chen_description.mp3',
  TextileChen: 'textile_chen_main.mp3',
  TextileBatikTech: 'textile_batik_tech.mp3',
  TextilePatchStuff: 'textile_patch_stuff.mp3',
  TextilePatchDescription: 'textile_patch_description.mp3',
  TextilePatch: 'textile_patch_main.mp3',
}
