export { Description as TextilePatchDescription } from './Description'
export { Main as TextilePatchMain } from './Main'
export { Sources as TextilePatchSources } from './Sources'
export { Stuff as TextilePatchStuff } from './Stuff'
export { Tech as TextilePatchTech } from './Tech'
export { Tools as TextilePatchTools } from './Tools'
export { Video as TextilePatchVideo } from './Video'
