export const SELECT_LANGUAGE = 'SELECT_LANGUAGE'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_SCALE = 'SET_SCALE'
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
